# Direct Preference Optimization
name: dpo
use_reference_model: true

# the temperature parameter for DPO; lower values mean we care less about the reference model
beta: 0.1

dataloader: 
  module_name: data.dataloader
  class_name: PairedPreferenceDataLoader

model:
  module_name: feature_alignment.model.dpo
  class_name: DPOModel